# docker-compose file pour le déploiement initial de l'application GeoQuizz
#
# ajouter les vhosts des services web dans le fichier /etc/vhosts
# de la machine hôte :
# exemple pour le service api.public :
# 127.0.0.1   api.geoquizz.local
# pour accéder à ce service :  http://api.geoquizz.local:10101
# accès au service adminer : http://localhost:8080
# accès au service mysql depuis le container api.public : utiliser le hostname "db"

version: "1"
networks:
  geoquizz_network:
    driver: bridge

services:
  api.public:
    image: canals/php
    container_name: api.public.geoquizz.local
    environment:
      - VHOST_HOSTNAME=api.geoquizz.local
      - VHOST_DOCROOT=/var/www/api
#     - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128/
#     - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128/
    ports:
      - "10101:80"
    volumes :
      - ./api:/var/www/api
      - ./src:/var/www/src
    networks:
      - geoquizz_network
    links :
      - mysql:db

#############################
# Backend de gestion
#############################
  api.gest:
    image: canals/php
    container_name: api.gest.geoquizz.local
    environment:
      - VHOST_HOSTNAME=gest.geoquizz.local
      - VHOST_DOCROOT=/var/www/gest
#     - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128/
#     - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128/
    ports:
      - "10111:80"
    volumes :
      - ./gest:/var/www/gest
      - ./src:/var/www/src
    networks:
      - geoquizz_network
    links :
      - mysql:db
      - api.public:api.public
#############################
# mysql + adminer
#############################
  mysql:
    image: mariadb:latest
    container_name: maria.geoquizz.local
    environment:
      - MYSQL_ROOT_PASSWORD=georoot
      - MYSQL_USER=geo
      - MYSQL_PASSWORD=geo
      - MYSQL_DATABASE=geoquizz
    ports:
      - "3603:3306"
    networks:
      - geoquizz_network
    volumes :
      - ./sql:/var/sql

  adminer:
     image: adminer
     container_name: admin.geoquizz.local
     ports:
       - "8080:8080"
     networks:
      - geoquizz_network
     links:
       - mysql:db
